from django.contrib import admin
from .models import *


admin.site.register(MainPage)
admin.site.register(MediaSections)
admin.site.register(Decress)
admin.site.register(Flight)
admin.site.register(BannerForAirlinesServices)
admin.site.register(AirlinesServices)
admin.site.register(AboutUs)
admin.site.register(AboutUsImage)
admin.site.register(AirlinesServicesRightBar)
admin.site.register(AirlinesServicesDown)
admin.site.register(AirlinesServicesBanner)
admin.site.register(AdministrationPage)
admin.site.register(Mission)
admin.site.register(AdministrationTable)
admin.site.register(Gallery)
admin.site.register(OnlineTableBanner)
admin.site.register(OnlineTaxesBanner)
admin.site.register(AllFlightBanner)
admin.site.register(AllFlight)
admin.site.register(Cargo)
admin.site.register(CargoPDF)
admin.site.register(Directions)
admin.site.register(DirectionsPlane)
admin.site.register(FlightCheck)
admin.site.register(Section)
admin.site.register(PDF)

