# Generated by Django 4.1.4 on 2022-12-14 13:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Buýruklaň ady')),
                ('media_image', models.ImageField(blank=True, null=True, upload_to='decress_image', verbose_name='Buýrugyň suraty')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Buýruklaryň giňişleýin beýany')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=10, null=True, verbose_name='Uçan wagty')),
                ('arrival', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gonan wagty')),
                ('flight_category', models.CharField(choices=[('DEPARTURE', 'Uçuş'), ('ARRIVAL', 'Gonuş')], default='DEPARTURE', max_length=15, verbose_name='Uçuş, Gonuş ?')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reýsyň ady')),
                ('model_plane', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uçaryň modeli')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_background', models.ImageField(blank=True, null=True, upload_to='banner_backg/', verbose_name='Banneryň arka fondaky suraty')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_image/', verbose_name='Banneryň esasy suraty(merkezdäki)')),
                ('mini_about', models.CharField(blank=True, max_length=255, null=True, verbose_name='Baş sahypadaky banneryň aşagyndaky gysgaça düşündiriş')),
                ('mini_about_image', models.ImageField(blank=True, null=True, upload_to='mini_about_image', verbose_name='Baş sahypadaky banneryň aşagyndaky gysgaça düşündiriň suraty')),
            ],
        ),
        migrations.CreateModel(
            name='MediaSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bildirişiň gysgaça ady')),
                ('category_media', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bildirişiň haýsy sektora degişliligi')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildirişiň beýany')),
                ('media_image', models.ImageField(blank=True, null=True, upload_to='media_image', verbose_name='Bildirişiň suraty')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
