# Generated by Django 4.1.4 on 2022-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_decress_flight_mainpage_mediasections_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decress',
            options={'verbose_name': 'Buýruk', 'verbose_name_plural': 'Buýruklar bölümi'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Üçuş-Gonuş', 'verbose_name_plural': 'Üçuş-Gonuşlar'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Baş sahypadaky banner we gysgaça maglumat', 'verbose_name_plural': 'Baş sahypadaky banner we gysgaça maglumatlar'},
        ),
        migrations.AlterModelOptions(
            name='mediasections',
            options={'verbose_name': 'Bildiriş', 'verbose_name_plural': 'Bildirişler bölümi'},
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_image',
            field=models.ImageField(blank=True, null=True, upload_to='flight_image', verbose_name='Reýsyň suraty'),
        ),
        migrations.AddField(
            model_name='mediasections',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Wideonyň ssylkasy'),
        ),
    ]
