# Generated by Django 4.1.4 on 2022-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_decress_options_alter_flight_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerForAirlinesServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bannerdaky esasy ýazgy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_airlines_services/', verbose_name='Banner suraty')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'H.M gulluklar bölüminäki banner',
            },
        ),
    ]
