# Generated by Django 4.1.4 on 2022-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_airlinesservices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinesservices',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
