# Generated by Django 4.1.4 on 2022-12-15 13:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_airlinesservices_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinesservices',
            name='full_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Doly beýany'),
        ),
        migrations.AlterField(
            model_name='airlinesservices',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gysgaça beýany'),
        ),
    ]
