# Generated by Django 4.1.4 on 2022-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mediasections_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bannerdaky esasy ýazgy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='Banner suraty')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'H.Menzil baradaky maglumat',
            },
        ),
    ]
