# Generated by Django 4.1.4 on 2022-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name=' suratyň ýazgysy ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='suraty')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'H.Menzil baradaky maglumat we taryhy suratlar',
            },
        ),
    ]
