# Generated by Django 4.1.4 on 2022-12-15 14:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aboutusimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Giňişleýin beýany'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_to_sections',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Esasy ýazgy taryh barada'),
        ),
        migrations.AlterField(
            model_name='aboutusimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='Suraty'),
        ),
        migrations.AlterField(
            model_name='aboutusimage',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Suratyň ýazgysy '),
        ),
    ]
