# Generated by Django 4.1.4 on 2022-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutus_description_aboutus_title_to_sections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlinesServicesDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hyzmatlar ýokarky ýazgysy')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hyzmatlar aşakdaky ýazgysy')),
            ],
            options={
                'verbose_name': 'Hyzmatlar',
                'verbose_name_plural': 'Hyzmatlar sahypasynyň maglumaty',
            },
        ),
        migrations.CreateModel(
            name='AirlinesServicesRightBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hyzmatlar sahypasynyň banner sag tarapy ýokarky')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hyzmatlar sahypasynyň banner sag tarapy aşakdaky')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon-services/', verbose_name='Ikonkasy')),
            ],
            options={
                'verbose_name': 'Hyzmatlar',
                'verbose_name_plural': 'Hyzmatlar sahypasynyň banner  maglumaty',
            },
        ),
    ]
