# Generated by Django 4.1.4 on 2022-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_airlinesservicesdown_airlinesservicesrightbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlinesServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Hyzmatlar sahypasynyň bannery')),
            ],
        ),
    ]
