# Generated by Django 4.1.4 on 2022-12-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_airlinesservicesbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlinesservicesbanner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Hyzmatlar sahypasynyň banner '},
        ),
    ]
