# Generated by Django 4.1.4 on 2022-12-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_airlinesservicesbanner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_background', models.ImageField(blank=True, null=True, upload_to='banner_backg/', verbose_name='Banneryň arka fondaky suraty')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_image/', verbose_name='Banneryň esasy suraty(merkezdäki)')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Administrasiýa sahypadaky banner ',
            },
        ),
    ]
