# Generated by Django 4.1.4 on 2022-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_administrationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wezipesi')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon belgisi')),
            ],
            options={
                'verbose_name': 'Wezipe',
                'verbose_name_plural': 'Administrasiýa wezipeleri Tablisasy',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wezipesi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Mission', verbose_name='Suraty')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon nomery')),
                ('phone_number_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon nomery(goşmaça)')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Elektron poçtasy')),
            ],
            options={
                'verbose_name': 'Wezipe',
                'verbose_name_plural': 'Administrasiýa wezipeleri ',
            },
        ),
    ]
