# Generated by Django 4.1.4 on 2022-12-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_administrationtable_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Suratyň ady')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Surat')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Gallereýa',
            },
        ),
    ]
