# Generated by Django 4.1.4 on 2022-12-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTableBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Banneryň üstindäki ýazgy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Online-Tablodaky banner',
            },
        ),
    ]
