# Generated by Django 4.1.4 on 2022-12-16 12:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_onlinetablebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTaxesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Banneryň üstindäki ýazgy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Banner')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Giňişleýin beýany')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Onlaýn sargytlaryň banner',
            },
        ),
    ]
