# Generated by Django 4.1.4 on 2022-12-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_onlinetaxesbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=10, null=True, verbose_name='Uçan wagty')),
                ('arrival', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gonan wagty')),
                ('flight_category', models.CharField(choices=[('DEPARTURE', 'Uçuş'), ('ARRIVAL', 'Gonuş')], default='DEPARTURE', max_length=15, verbose_name='Uçuş, Gonuş ?')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reýsyň ady')),
                ('model_plane', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uçaryň modeli')),
                ('flight_day', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uçýan günleri')),
            ],
            options={
                'verbose_name': 'Üçuş-Gonuş',
                'verbose_name_plural': 'Ahli uçuş-Gonuşlar',
            },
        ),
        migrations.CreateModel(
            name='AllFlightBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Banneryň üstindäki ýazgy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='all-flight/', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Gatnawlaň rejesi',
            },
        ),
        migrations.AlterField(
            model_name='onlinetablebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='online-table/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='onlinetaxesbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='online-taxes/', verbose_name='Banner'),
        ),
    ]
