# Generated by Django 4.1.4 on 2022-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_allflight_allflightbanner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allflightbanner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Gatnawlaň rejesi bannery'},
        ),
        migrations.AlterField(
            model_name='allflightbanner',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Banneryň üstindäki ýazgy'),
        ),
    ]
