# Generated by Django 4.1.4 on 2022-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cargopdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='dowlaod_icon',
            field=models.ImageField(blank=True, null=True, upload_to='dowload_icon/', verbose_name='Pdf skaçat etmek düwmesi'),
        ),
    ]
