# Generated by Django 4.1.4 on 2022-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_aboutus_dowlaod_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargopdf',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Filyň ady'),
        ),
    ]
