# Generated by Django 4.1.4 on 2022-12-16 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_cargopdf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ugurlar banner üstindäki ýazgy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='directions/', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Ugurlar baradaky sahypa baradaky banner',
            },
        ),
        migrations.CreateModel(
            name='DirectionsPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ugruň ady')),
                ('image', models.ImageField(blank=True, null=True, upload_to='directions_plane/', verbose_name='Suraty')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Giňişleýin beýany')),
            ],
            options={
                'verbose_name': 'Ugur',
                'verbose_name_plural': 'Ugur goşmak',
            },
        ),
        migrations.AlterField(
            model_name='cargopdf',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Filyň ady'),
        ),
    ]
