# Generated by Django 4.1.4 on 2022-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_section_alter_flightcheck_name_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cat',
            field=models.CharField(choices=[('HYZMATDAŞLARA', 'Hyzmatdaşlara'), ('HYZMATLAR', 'Hyzmatlar')], default='HYZMATDAŞLARA', max_length=150, verbose_name='Haýsy menýu degişli ?'),
        ),
    ]
