# Generated by Django 4.1.4 on 2022-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_section_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Banneryň üstindäki ýazgy'),
        ),
    ]
